name: Maven CI

on:
  workflow_dispatch: { }
  push: { }
  pull_request: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          paths_ignore: '[ "**/*.md", "**/*.adoc" ]'
          cancel_others: true
          concurrent_skipping: outdated_runs
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build application with Maven
        shell: bash
        run: |
          ./mvnw \
            --show-version \
            --errors \
            --batch-mode \
            --no-transfer-progress \
            verify jacoco:merge@jacoco-merge-cli site \
            -Pdocs \
            -DtrimStackTrace=false

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true # optional (default = false)
