name: Maven with Apache Johnzon and Apache CXF

on:
  workflow_dispatch: { }
  push: { }
  pull_request: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build application with Maven using Apache Johnzon and Apache CXF
        shell: bash
        run: ./mvnw --show-version --errors --batch-mode --no-transfer-progress verify -Pdocs,json-johnzon,jaxrs-cxf -DtrimStackTrace=false
